//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MIBRes.rc
//
#define IDS_ENV_STRING                  1
#define IDS_COMMENT                     2
#define IDS_IPADDR_SECTION_NAME         3
#define IDS_IPADDR_SECTION_FORMAT       4
#define IDS_HIDE_OUTPUT_STR             5
#define IDS_SHOW_OUTPUT_STR             6
#define IDS_TOOLSDIRNAME                7
#define IDS_GETTABLE_EXE_NAME           8
#define IDS_SETANY_EXE_NAME             9
#define IDS_GETONE_EXE_NAME             10
#define IDS_CONSOLETITLE_PREFIX         11
#define IDS_GETMANY_EXE_NAME            12
#define IDS_MAINWINDOWTITLE             13
#define IDS_CONSOLE_TITLE               14
#define IDS_COMMENT2                    15
#define MSG_CREATEPROCFAILED            16
#define MSG_CONSOLEHANDLEINVALID        17
#define MSG_CONSOLEREADERROR            18
#define MSG_COMMANDFAILED               19
#define IDS_GETONE_HEADER               20
#define IDS_GETMANY_HEADER              21
#define IDS_GETTABLE_HEADER             22
#define IDS_SETANY_HEADER               23
#define IDS_SETANY_HEADER2              24
#define IDS_OUTPUT_FOOTER               25
#define IDS_COMMUNITY_NAME              26
#define IDS_COMMUNITY_ENV_VAR           27
#define MSG_CREATEPROCFAILED_LOG        28
#define MNU_SHOW_CHECK                  29
#define MNU_HIDE_CHECK                  30
#define IDS_INACTIVE_CONTROL_STRING     31
#define IDI_ICON2                       100
#define IDR_APPICON                     100
#define IDD_MAIN_DIALOG                 101
#define IDB_BITMAP1                     103
#define IDB_BITMAP2                     104
#define IDB_BITMAP3                     105
#define IDB_BITMAP4                     106
#define IDB_BITMAP5                     107
#define IDB_BITMAP6                     108
#define IDB_BITMAP7                     109
#define IDB_BITMAP8                     110
#define IDB_BITMAP9                     111
#define IDB_BITMAP10                    112
#define IDR_MAIN_MENU                   114
#define IDB_BITMAP11                    117
#define IDB_BITMAP12                    125
#define IDD_ENV_VAR_DLG                 126
#define IDD_SPLASH                      127
#define IDB_RTSLOGO                     129
#define IDD_SYNTAX_DLG                  130
#define IDB_PROGRAM_NAME                134
#define IDB_RTSLOGO256                  135
#define IDD_FIND_DIALOG                 136
#define IDR_ACCELERATORS                137
#define IDB_PROGRAM_LOGO                138
#define IDB_BITMAP13                    139
#define IDD_UTILITIES_DLG               140
#define IDC_BUTTON1                     1000
#define IDD_CLOSE_BTN                   1000
#define IDC_GETONE_BTN                  1000
#define IDC_MIB_TREE                    1001
#define IDC_STATUS_BOX                  1004
#define IDC_TEXTUAL_OID_LABEL           1005
#define IDC_SYNTAX_LABEL                1006
#define IDC_ACCESS_LABEL                1007
#define IDC_INDEX_LABEL                 1008
#define IDC_STATUS_LABEL                1009
#define IDC_NUMERIC_OID_LABEL           1010
#define IDC_DESCRIPTION_LABEL           1011
#define IDC_EXTRAINFO_LABEL             1012
#define IDC_STATIC_STATUS_MESSAGES      1013
#define IDC_STATIC_OID_TEXT             1014
#define IDC_STATIC_OID_NUM              1015
#define IDC_STATIC_SYNTAX               1016
#define IDC_STATIC_ACCESS               1017
#define IDC_STATIC_INDEX                1018
#define IDC_STATIC_OBJECT_STATUS        1019
#define IDC_STATIC_DESCRIPTION          1020
#define IDC_STATIC_EXTRA_INFO           1021
#define IDC_CLEAR_STAT_BTN              1022
#define IDC_ENV_EDIT                    1023
#define IDC_STATIC_SHORT_OID_TEXT       1023
#define IDC_SHORT_OID_LABEL             1024
#define IDC_RTS_LOGO                    1025
#define IDC_ELEMENT_NAME                1026
#define IDC_ELEMENT_SYNTAX              1027
#define IDC_SYNTAX_DEF                  1028
#define IDC_PROGRAM_NAME                1030
#define ID_FIND_BTN                     1031
#define ID_FIND_NEXT_BTN                1032
#define IDC_FIND_STRING_EDIT_BOX        1033
#define IDC_CASE_SENSITIVE_CHK          1034
#define IDC_IP_ADDRESS_COMBOBOX         1036
#define IDC_DATATYPE_COMBOBOX           1038
#define IDC_GETTABLE_BTN                1039
#define IDC_SETANY_BTN                  1040
#define IDC_ELEMENTNAME_EDIT            1041
#define IDC_DATAVALUE_EDIT              1042
#define IDC_CLEARALL_BTN                1043
#define IDC_FIND_BTN                    1044
#define IDC_SYNTAX_BTN                  1045
#define IDC_UTILITIES_BTN               1046
#define IDC_SHOWOUTPUT_BTN              1047
#define IDC_OUTPUT_EDIT                 1048
#define IDC_CLEAR_CONTENS_BTN           1049
#define IDC_GETMANY_BTN                 1050
#define IDC_AUTOCOMPLETE_CBX            1052
#define IDC_BUTTON2                     1053
#define ID_FILE_LOAD_NEW_MIB            40006
#define ID_EDIT_NOCOMMAND               40007
#define ID_HELP_NOCOMMAND               40008
#define ID_TEST_DEBUGTEST               40011
#define ID_FILE_UNLOADSELECTEDMIB       40012
#define ID_FILE_UNLOADALLMIBS           40013
#define ID_FILE_EXIT                    40014
#define ID_BATCH_SETENVIRONMENTVARIABLENAME 40015
#define ID_BATCH_LOADMIBSFROMTHEVARIABLE 40016
#define ID_EDIT_SHOWELEMENTSYNTAX       40017
#define ID_EDIT_FIND_ELEMENTBYNAME      40018
#define IDR_ACCEL_FIND                  40019
#define ID_EDIT_UTILITIES               40020
#define ID_MISCELLANEOUS_SHOWCHECKBOXES 40021

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         40022
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
