/*
 *
 * Copyright (C) 1992-1998 by SNMP Research, Incorporated.
 *
 * This software is furnished under a license and may be used and copied
 * only in accordance with the terms of such license and with the
 * inclusion of the above copyright notice. This software or any other
 * copies thereof may not be provided or otherwise made available to any
 * other person. No title to and ownership of the software is hereby
 * transferred.
 *
 * The information in this software is subject to change without notice
 * and should not be construed as a commitment by SNMP Research, Incorporated.
 *
 * Restricted Rights Legend:
 *  Use, duplication, or disclosure by the Government is subject to
 *  restrictions as set forth in subparagraph (c)(1)(ii) of the Rights
 *  in Technical Data and Computer Software clause at DFARS 252.227-7013;
 *  subparagraphs (c)(4) and (d) of the Commercial Computer
 *  Software-Restricted Rights Clause, FAR 52.227-19; and in similar
 *  clauses in the NASA FAR Supplement and other corresponding
 *  governmental regulations.
 *
 */

/*
 *                PROPRIETARY NOTICE
 *
 * This software is an unpublished work subject to a confidentiality agreement
 * and is protected by copyright and trade secret law.  Unauthorized copying,
 * redistribution or other use of this work is prohibited.
 *
 * The above notice of copyright on this source code product does not indicate
 * any actual or intended publication of such source code.
 */


/*
 * Arguments used to create this file:
 * -o v2 -test_and_incr -parser -row_status -userpart -storage_type 
 * -ansi 
 */

/* $Id: v2defs.h,v 1.4 1998/01/07 22:04:07 mark Exp $ */

/*
 * File Description:
 */

/*
 * automatically generated by the mib compiler -- do not edit
 */

#ifndef SR_V2DEFS_H
#define SR_V2DEFS_H


#ifdef __cplusplus
extern "C" {
#endif

/* enumerated values for srCommunityMemoryType */
#define D_srCommunityMemoryType_other    1
#define D_srCommunityMemoryType_volatile 2
#define D_srCommunityMemoryType_nonVolatile 3
#define D_srCommunityMemoryType_permanent 4
#define D_srCommunityMemoryType_readOnly 5
#define D_srCommunityMemoryType_other    1
#define D_srCommunityMemoryType_volatile 2
#define D_srCommunityMemoryType_nonVolatile 3
#define D_srCommunityMemoryType_permanent 4
#define D_srCommunityMemoryType_readOnly 5

/* enumerated values for srCommunityStatus */
#define D_srCommunityStatus_active       1
#define D_srCommunityStatus_notInService 2
#define D_srCommunityStatus_notReady     3
#define D_srCommunityStatus_createAndGo  4
#define D_srCommunityStatus_createAndWait 5
#define D_srCommunityStatus_destroy      6

/* enumerated values for v2ContextLocalTime */
#define D_v2ContextLocalTime_currentTime 1
#define D_v2ContextLocalTime_restartTime 2

/* enumerated values for v2ContextMemoryType */
#define D_v2ContextMemoryType_other    1
#define D_v2ContextMemoryType_volatile 2
#define D_v2ContextMemoryType_nonVolatile 3
#define D_v2ContextMemoryType_permanent 4
#define D_v2ContextMemoryType_readOnly 5
#define D_v2ContextMemoryType_other    1
#define D_v2ContextMemoryType_volatile 2
#define D_v2ContextMemoryType_nonVolatile 3
#define D_v2ContextMemoryType_permanent 4
#define D_v2ContextMemoryType_readOnly 5

/* enumerated values for v2ContextStatus */
#define D_v2ContextStatus_active       1
#define D_v2ContextStatus_notInService 2
#define D_v2ContextStatus_notReady     3
#define D_v2ContextStatus_createAndGo  4
#define D_v2ContextStatus_createAndWait 5
#define D_v2ContextStatus_destroy      6

/* enumerated values for viewTreeType */
#define D_viewTreeType_included        1
#define D_viewTreeType_excluded        2

/* enumerated values for viewTreeMemoryType */
#define D_viewTreeMemoryType_other     1
#define D_viewTreeMemoryType_volatile  2
#define D_viewTreeMemoryType_nonVolatile 3
#define D_viewTreeMemoryType_permanent 4
#define D_viewTreeMemoryType_readOnly  5
#define D_viewTreeMemoryType_other     1
#define D_viewTreeMemoryType_volatile  2
#define D_viewTreeMemoryType_nonVolatile 3
#define D_viewTreeMemoryType_permanent 4
#define D_viewTreeMemoryType_readOnly  5

/* enumerated values for viewTreeStatus */
#define D_viewTreeStatus_active        1
#define D_viewTreeStatus_notInService  2
#define D_viewTreeStatus_notReady      3
#define D_viewTreeStatus_createAndGo   4
#define D_viewTreeStatus_createAndWait 5
#define D_viewTreeStatus_destroy       6

/* enumerated values for acSPI */
#define D_acSPI_snmpv1                 1
#define D_acSPI_snmpv2C                2
#define D_acSPI_maint                  3
#define D_acSPI_usecNoAuth             4
#define D_acSPI_usecAuth               5
#define D_acSPI_usecPriv               6
#define D_acSPI_snmpv1                 1
#define D_acSPI_snmpv2C                2
#define D_acSPI_maint                  3
#define D_acSPI_usecNoAuth             4
#define D_acSPI_usecAuth               5
#define D_acSPI_usecPriv               6

/* enumerated values for acPrivs */
#define D_acPrivs_nothing              1
#define D_acPrivs_readOnly             2
#define D_acPrivs_readWrite            3

/* enumerated values for acMemoryType */
#define D_acMemoryType_other           1
#define D_acMemoryType_volatile        2
#define D_acMemoryType_nonVolatile     3
#define D_acMemoryType_permanent       4
#define D_acMemoryType_readOnly        5
#define D_acMemoryType_other           1
#define D_acMemoryType_volatile        2
#define D_acMemoryType_nonVolatile     3
#define D_acMemoryType_permanent       4
#define D_acMemoryType_readOnly        5

/* enumerated values for acStatus */
#define D_acStatus_active              1
#define D_acStatus_notInService        2
#define D_acStatus_notReady            3
#define D_acStatus_createAndGo         4
#define D_acStatus_createAndWait       5
#define D_acStatus_destroy             6

/* enumerated values for transportMemoryType */
#define D_transportMemoryType_other    1
#define D_transportMemoryType_volatile 2
#define D_transportMemoryType_nonVolatile 3
#define D_transportMemoryType_permanent 4
#define D_transportMemoryType_readOnly 5
#define D_transportMemoryType_other    1
#define D_transportMemoryType_volatile 2
#define D_transportMemoryType_nonVolatile 3
#define D_transportMemoryType_permanent 4
#define D_transportMemoryType_readOnly 5

/* enumerated values for transportStatus */
#define D_transportStatus_active       1
#define D_transportStatus_notInService 2
#define D_transportStatus_notReady     3
#define D_transportStatus_createAndGo  4
#define D_transportStatus_createAndWait 5
#define D_transportStatus_destroy      6

/* enumerated values for notifySPI */
#define D_notifySPI_snmpv1             1
#define D_notifySPI_snmpv2C            2
#define D_notifySPI_maint              3
#define D_notifySPI_usecNoAuth         4
#define D_notifySPI_usecAuth           5
#define D_notifySPI_usecPriv           6
#define D_notifySPI_snmpv1             1
#define D_notifySPI_snmpv2C            2
#define D_notifySPI_maint              3
#define D_notifySPI_usecNoAuth         4
#define D_notifySPI_usecAuth           5
#define D_notifySPI_usecPriv           6

/* enumerated values for notifyMemoryType */
#define D_notifyMemoryType_other       1
#define D_notifyMemoryType_volatile    2
#define D_notifyMemoryType_nonVolatile 3
#define D_notifyMemoryType_permanent   4
#define D_notifyMemoryType_readOnly    5
#define D_notifyMemoryType_other       1
#define D_notifyMemoryType_volatile    2
#define D_notifyMemoryType_nonVolatile 3
#define D_notifyMemoryType_permanent   4
#define D_notifyMemoryType_readOnly    5

/* enumerated values for notifyStatus */
#define D_notifyStatus_active          1
#define D_notifyStatus_notInService    2
#define D_notifyStatus_notReady        3
#define D_notifyStatus_createAndGo     4
#define D_notifyStatus_createAndWait   5
#define D_notifyStatus_destroy         6

/* enumerated values for notifyConfirm */
#define D_notifyConfirm_true           1
#define D_notifyConfirm_false          2

/* enumerated values for proxyType */
#define D_proxyType_gnb                1
#define D_proxyType_set                2
#define D_proxyType_trap               3
#define D_proxyType_inform             4

/* enumerated values for proxySPIIn */
#define D_proxySPIIn_snmpv1            1
#define D_proxySPIIn_snmpv2C           2
#define D_proxySPIIn_maint             3
#define D_proxySPIIn_usecNoAuth        4
#define D_proxySPIIn_usecAuth          5
#define D_proxySPIIn_usecPriv          6
#define D_proxySPIIn_snmpv1            1
#define D_proxySPIIn_snmpv2C           2
#define D_proxySPIIn_maint             3
#define D_proxySPIIn_usecNoAuth        4
#define D_proxySPIIn_usecAuth          5
#define D_proxySPIIn_usecPriv          6

/* enumerated values for proxySPIOut */
#define D_proxySPIOut_snmpv1           1
#define D_proxySPIOut_snmpv2C          2
#define D_proxySPIOut_maint            3
#define D_proxySPIOut_usecNoAuth       4
#define D_proxySPIOut_usecAuth         5
#define D_proxySPIOut_usecPriv         6
#define D_proxySPIOut_snmpv1           1
#define D_proxySPIOut_snmpv2C          2
#define D_proxySPIOut_maint            3
#define D_proxySPIOut_usecNoAuth       4
#define D_proxySPIOut_usecAuth         5
#define D_proxySPIOut_usecPriv         6

/* enumerated values for proxyMemoryType */
#define D_proxyMemoryType_other        1
#define D_proxyMemoryType_volatile     2
#define D_proxyMemoryType_nonVolatile  3
#define D_proxyMemoryType_permanent    4
#define D_proxyMemoryType_readOnly     5
#define D_proxyMemoryType_other        1
#define D_proxyMemoryType_volatile     2
#define D_proxyMemoryType_nonVolatile  3
#define D_proxyMemoryType_permanent    4
#define D_proxyMemoryType_readOnly     5

/* enumerated values for proxyStatus */
#define D_proxyStatus_active           1
#define D_proxyStatus_notInService     2
#define D_proxyStatus_notReady         3
#define D_proxyStatus_createAndGo      4
#define D_proxyStatus_createAndWait    5
#define D_proxyStatus_destroy          6

/* enumerated values for userMemoryType */
#define D_userMemoryType_other         1
#define D_userMemoryType_volatile      2
#define D_userMemoryType_nonVolatile   3
#define D_userMemoryType_permanent     4
#define D_userMemoryType_readOnly      5
#define D_userMemoryType_other         1
#define D_userMemoryType_volatile      2
#define D_userMemoryType_nonVolatile   3
#define D_userMemoryType_permanent     4
#define D_userMemoryType_readOnly      5

/* enumerated values for userStatus */
#define D_userStatus_active            1
#define D_userStatus_notInService      2
#define D_userStatus_notReady          3
#define D_userStatus_createAndGo       4
#define D_userStatus_createAndWait     5
#define D_userStatus_destroy           6


#ifdef __cplusplus
}
#endif

/* DO NOT PUT ANYTHING AFTER THIS #endif */
#endif /* SR_V2DEFS_H */
