/*
 *
 * Copyright (C) 1992-1998 by SNMP Research, Incorporated.
 *
 * This software is furnished under a license and may be used and copied
 * only in accordance with the terms of such license and with the
 * inclusion of the above copyright notice. This software or any other
 * copies thereof may not be provided or otherwise made available to any
 * other person. No title to and ownership of the software is hereby
 * transferred.
 *
 * The information in this software is subject to change without notice
 * and should not be construed as a commitment by SNMP Research, Incorporated.
 *
 * Restricted Rights Legend:
 *  Use, duplication, or disclosure by the Government is subject to
 *  restrictions as set forth in subparagraph (c)(1)(ii) of the Rights
 *  in Technical Data and Computer Software clause at DFARS 252.227-7013;
 *  subparagraphs (c)(4) and (d) of the Commercial Computer
 *  Software-Restricted Rights Clause, FAR 52.227-19; and in similar
 *  clauses in the NASA FAR Supplement and other corresponding
 *  governmental regulations.
 *
 */

/*
 *                PROPRIETARY NOTICE
 *
 * This software is an unpublished work subject to a confidentiality agreement
 * and is protected by copyright and trade secret law.  Unauthorized copying,
 * redistribution or other use of this work is prohibited.
 *
 * The above notice of copyright on this source code product does not indicate
 * any actual or intended publication of such source code.
 */


/*
 * Arguments used to create this file:
 * -o v2 -test_and_incr -parser -row_status -userpart -storage_type 
 * -ansi 
 */

/* $Id: v2supp.h,v 1.4 1998/01/07 22:04:25 mark Exp $ */

/*
 * File Description:
 */

/*
 * If your implementation does NOT support a MIB variable, add a line in
 * the undefs.h file containing #undef I_that-variable-name.  For example,
 * if you do not support the sysDescr variable in the system family
 * add a line:
 *
 * #undef I_sysDescr
 *
 *
 */


/*
 * automatically generated by the mib compiler -- do not edit
 */

#ifndef SR_V2SUPP_H
#define SR_V2SUPP_H


#ifdef __cplusplus
extern "C" {
#endif

#define I_srCommunitySpinLock                                 0

#define I_srCommunityAuthSnmpID                               0
#define I_srCommunityName                                     1
#define I_srCommunityGroupName                                2
#define I_srCommunityContextSnmpID                            3
#define I_srCommunityContextName                              4
#define I_srCommunityTransportLabel                           5
#define I_srCommunityMemoryType                               6
#define I_srCommunityStatus                                   7

#define I_snmpID                                            0
#define I_snmpMaxMessageSize                                1
#define I_maxIdentityNameLength                             2
#define I_maxGroupNameLength                                3
#define I_maxV2ContextNameLength                            4
#define I_maxViewTreeNameLength                             5
#define I_maxTransportLabelLength                           6

#define I_v2AdminStatsUnknownSPIs                           0
#define I_v2AdminStatsUnknownContexts                       1
#define I_v2AdminStatsUnavailableContexts                   2
#define I_v2AdminStatsCacheMisses                           3

#define I_v2ContextSnmpID                                   0
#define I_v2ContextName                                     1
#define I_v2ContextLocalEntity                              2
#define I_v2ContextLocalTime                                3
#define I_v2ContextMemoryType                               4
#define I_v2ContextStatus                                   5

#define I_viewTreeSpinLock                                  0

#define I_viewTreeName                                      0
#define I_viewTreeSubTree                                   1
#define I_viewTreeMask                                      2
#define I_viewTreeType                                      3
#define I_viewTreeMemoryType                                4
#define I_viewTreeStatus                                    5

#define I_acSpinLock                                        0

#define I_acSPI                                             0
#define I_acGroupName                                       1
#define I_acContextName                                     2
#define I_acContextNameMask                                 3
#define I_acPrivs                                           4
#define I_acReadViewName                                    5
#define I_acWriteViewName                                   6
#define I_acMemoryType                                      7
#define I_acStatus                                          8

#define I_transportSpinLock                                 0

#define I_transportLabel                                    0
#define I_transportSubindex                                 1
#define I_transportDomain                                   2
#define I_transportAddress                                  3
#define I_transportReceiveMask                              4
#define I_transportMMS                                      5
#define I_transportMemoryType                               6
#define I_transportStatus                                   7

#define I_notifySpinLock                                    0

#define I_notifyIndex                                       0
#define I_notifySPI                                         1
#define I_notifyIdentityName                                2
#define I_notifyTransportLabel                              3
#define I_notifyContextName                                 4
#define I_notifyViewName                                    5
#define I_notifyMemoryType                                  6
#define I_notifyStatus                                      7
#define I_notifyConfirm                                     8
#define I_notifyAuthSnmpID                                  9
#define I_notifyTimeout                                     10
#define I_notifyMaxRetry                                    11


#define I_proxyIndex                                        0
#define I_proxyType                                         1
#define I_proxySPIIn                                        2
#define I_proxyAuthSnmpIDIn                                 3
#define I_proxyIdentityNameIn                               4
#define I_proxyContextSnmpIDIn                              5
#define I_proxyContextNameIn                                6
#define I_proxySPIOut                                       7
#define I_proxyIdentityNameOut                              8
#define I_proxyTransportLabelOut                            9
#define I_proxyMemoryType                                   10
#define I_proxyStatus                                       11

#define I_snmpBoots                                         0
#define I_snmpTime                                          1

#define I_usecStatsNotInTimeWindows                         0
#define I_usecStatsUnknownUserNames                         1
#define I_usecStatsWrongDigestValues                        2
#define I_usecStatsBadPrivacys                              3

#define I_userSpinLock                                      0
#define I_maxUserNameLength                                 1

#define I_userAuthSnmpID                                    0
#define I_userName                                          1
#define I_userGroupName                                     2
#define I_userAuthChange                                    3
#define I_userPrivChange                                    4
#define I_userNovel                                         5
#define I_userTransportLabel                                6
#define I_userCloneFrom                                     7
#define I_userMemoryType                                    8
#define I_userStatus                                        9

#include "snmpv2s/undefs.h"


#ifdef __cplusplus
}
#endif

/* DO NOT PUT ANYTHING AFTER THIS #endif */
#endif /* SR_V2SUPP_H */
